name: example
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3

  direct_link:
    path: ../
  cached_network_image: ^3.4.1
  file_picker: ^10.3.6
  go_router: ^17.0.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  riverpod_generator: ^3.0.3
  build_runner: ^2.4.15
  custom_lint: ^0.8.1
  riverpod_lint: ^3.0.3
  very_good_analysis: ^10.0.0
  go_router_builder: ^4.1.1

flutter:
  uses-material-design: true
