name: direct_link
description: Direct link extractor from URL to stream and download directly.
version: 0.3.3
repository: https://github.com/thitlwincoder/direct_link
issue_tracker: https://github.com/thitlwincoder/direct_link/issues

environment:
  sdk: ^3.10.0

platforms:
  android:
  ios:
  web:
  linux:
  macos:
  windows:

funding:
  - https://paypal.me/thitlwinsoe260
  - https://ko-fi.com/thitlwincoder

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ^6.1.5
  html: ^0.15.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
